version: 2.1
commands:
    fetch-opam:
        steps:
            - restore_cache:
                name: Restore opam cache
                keys:
                    - opam-linux-v1-{{ checksum "opam.export" }}

jobs:
    build-opam-cache:
        docker:
        # For now, just reuse coda's Docker toolchain. In the future, we should compose Coda's from Snarky's somehow
        - image: gcr.io/o1labs-192920/mina-toolchain@sha256:72fd8954d9f4f13e8596c3826c570e8fcd8473ec0091cbbfba17c9366e983e0b
        steps:
            - checkout
            - restore_cache:
                name: Restore opam cache
                keys:
                    - opam-linux-v1-{{ checksum "opam.export" }}
            - run:
                name: Install opam deps
                command: scripts/build-opam.sh
            - save_cache:
                name: Save opam cache
                key: opam-linux-v1-{{ checksum "opam.export" }}
                paths:
                    - "/home/opam/.opam"
    build:
        docker:
        # For now, just reuse coda's Docker toolchain. In the future, we should compose Coda's from Snarky's somehow
        - image: gcr.io/o1labs-192920/mina-toolchain@sha256:72fd8954d9f4f13e8596c3826c570e8fcd8473ec0091cbbfba17c9366e983e0b
        steps:
            - checkout
            - fetch-opam
            - run: eval `opam config env` && make build
            - run: eval `opam config env` && make tests
    opam-pin:
        docker:
        # For now, just reuse coda's Docker toolchain. In the future, we should compose Coda's from Snarky's somehow
        - image: gcr.io/o1labs-192920/mina-toolchain@sha256:72fd8954d9f4f13e8596c3826c570e8fcd8473ec0091cbbfba17c9366e983e0b
        steps:
            - checkout
            - fetch-opam
            - run:
                name: opam pin
                command: eval `opam config env` && opam pin .
    website:
        docker:
        - image: node
        steps:
            - checkout
            - run:
                name: Test a release build of the website
                command: make test-website-build
workflows:
    version: 2
    snarky_parallel:
        jobs:
        - website
        - build-opam-cache
        - build:
             requires:
                - build-opam-cache
        - opam-pin:
             requires:
                - build-opam-cache
